from src.utilities.image_utils import calculate_LoG
import numpy as np
import napari
import glob2 as glob
import os
import skimage.io as io
import zarr

root = "E:\\Nick\Cole Trapnell's Lab Dropbox\\Nick Lammers\\Nick\pecfin_dynamics\\fin_morphodynamics\\"

experiment_date = "20240223"
model_name = "log-v5"
label_directory = os.path.join(root, "built_data", "cellpose_output", model_name, experiment_date, '')
data_directory = os.path.join(root, "built_data", "zarr_image_files", experiment_date, '')

# get list of images
image_list = sorted(glob.glob(data_directory + "*.zarr"))
time_int = 201
well_int = 2

# load raw data
data_tzyx = zarr.open(image_list[well_int], mode="r")
data_zyx = np.squeeze(data_tzyx[time_int, :, :, :])

dtype = data_zyx.dtype
scale_vec = tuple([2.0, 0.55, 0.55])

# load the origianl labels and probs generated by CellPose
prob_name = experiment_date + f"_well{well_int:03}_t{time_int:03}_probs.tif"
label_name = experiment_date + f"_well{well_int:03}_t{time_int:03}_labels.tif"

prob_path = os.path.join(label_directory, prob_name)
im_prob = io.imread(prob_path)
label_path = os.path.join(label_directory, label_name)
im_label = io.imread(label_path)

# Crop to a more managable size
data_cropped = data_zyx[:, 340:590, 90:270]
labels_cropped = im_label[:, 340:590, 90:270]
probs_cropped = im_prob[:, 340:590, 90:270]

im_LoG, im_bkg = calculate_LoG(data_cropped, scale_vec, make_anisotropic=True)

viewer = napari.view_image(im_LoG)